# Use the Ubuntu base image
FROM ubuntu

# Update package lists and install necessary packages
RUN apt-get update && \
    apt-get install -y vim ansible && \
    apt-get upgrade -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /etc/ansible

# Command to run when the container starts
CMD ["/bin/bash"]
