apiVersion: v1
kind: Pod
metadata:
  name: mysql-for-foodly
  labels:
    app: mysql-for-foodly
    namespace: foodly
spec:
  containers:
  - name: mysql
    image: mysql:latest
    ports:
    - containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: "123123"